# SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 blobadoodle <me@bloba.dev>
# SPDX-FileCopyrightText: 2025 coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

- type: startingGear # Goobstation - Start - Sol
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryColorLightBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasCentcom
    neck: ExecutiveIDCard # Executive Access!
    eyes: ClothingEyesGlassesCentComm # Better glasses
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    id: CBURNPDA # Todo - Replace it.
    pocket1: InfectionScannerCburn # Goob
    pocket2: WeaponAdvancedLaser
    belt: ClothingBeltSecurityFilled # No shotgun, no bandolier.
  storage:
    back:
    - WeaponShotgunAntelope
    - BoxShotgunIncendiary
    - BoxShotgunIncendiary
    - MagazineShotgunIncendiary
    - MagazineShotgunIncendiary
    - MagazineShotgunIncendiary
    - MagazineShotgunIncendiary
    - SelfRechargingFireExtinguisher
    - GrenadeIncendiary
    - AmbuzolPlusMedipen # Injectors are cooler.
    - AmbuzolMedipen # Injectors are cooler.
    - AmbuzolMedipen # Injectors are cooler.
    - MedkitCombatFilled # Ah yes, let's send them in with ZERO meds. Good luck!
  inhand:
  - CburnSpear
# Goobstation - End - Sol
