- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  whitelisted: true
  startingGear: PrisonerGear
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  canBeAntag: true

- type: startingGear
  id: PrisonerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBrown
    ears: ClothingHeadsetGrey
